# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c84dc3c702c5cce4f90ea3c14f7c9cd1888d2de1ce3aa8cb09c6e7ce05784fce3701d3db19fc0b1f82ab38760867d73a291a4f149b78123805d38ea21eb0656e

test:
  secret_key_base: 7525d3a6448ade67c128355a03083982d1fbb1c00ac82c9b27bc4e314905cc617a4afc183c820a20167e1b4a5976170c461bc5661f081172ba4fef7b28466f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
